### ISSUE TITLE
Hangouts Call Apr 5

### ISSUE THREAD

**Issue by gaurav-naik** [mntechnique/kisanmitra_erpnext#6]
- [x] Lookup linked issues from Lead.
- [x] Popup should be seen only by the User. (Look into call divert flow to get user number)
- [x] First cut of Dashboard.
- [x] Release Data Import tool
- [x] Unable to see Call recording link on Communications.  
- [x] Activate production server
  - [x] Import data via import tool.
- [x] User Permissions (Desk access)
- [x] Territory Import & Mapping to Roles/User Permissions
- [ ] Reporting
- [x] Write the steps for flow explanations. Main flow and in case of downtime/failure plan B as a workaround
- [x] Link a call communication even if it is an inquiry call for an existing Issue.
- [ ] Sms Alerts & workflow integration

Task

@nanoharsha @unmesh87 @saurabh-bhosale @kothagunda

**Comment by gaurav-naik** [comment]
- [x] Departments from vTiger Data
- [x] Issue Status from vTiger data
- [ ] Testing
  - [ ] Call Type to Issue Type mapping?
  - [x] Case Category as List
  - [ ] Caste as List
  - [x] District, Village and Mandal as Link to Territory

**Comment by nanoharsha** [comment]
Employees have been created so that Cases can be assigned to users from To-Do in the Issue page.
But in the Employee the data imported lacks consistency, leading to unable to use the common properties of a Employee Role. I think so Roles should be universal across Districts, and there should be an additional column for Location which will distinguish a Tahsildar of a mandal at one district to another. 
Also as mentioned above, across districts the Roles should be common, so that if we want to arrange a certain property to a role, it can be done easily.

**Comment by gaurav-naik** [comment]
Closing issue as facts have changed since the last update.
